version: "3"

services:
    chrome:
        # image: alpine:latest
        build: .
        container_name: chrome_container
        network_mode: bridge
        ports: 
            - "5566:5566"
        # restart: on-failure
        privileged: true
        volumes: 
            - ./resources:/*
