version: "3"

services:
    browser:
        # image: alpine:latest
        build: .
        container_name: browser_container
        network_mode: bridge
        ports: 
            - "5566:5566"
        # restart: on-failure
        privileged: true
        environment:
            #  Using: $ip:0
            - DISPLAY=192.168.1.196:0
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-uni
